site_name: Digiforms Documentation

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
  - Designer:
      - designer/index.md
  - Server:
      - server/index.md

      


